ET_INCIDENT_REPORTED = "IncidentReported"
ET_INCIDENT_DISPATCHED = "IncidentDispatched"
ET_INCIDENT_MONITORED = "IncidentMonitored"
ET_INCIDENT_ACKNOWLEDGED = "IncidentAcknowledged"
ET_INCIDENT_ESCALATED = "IncidentEscalated"
ET_INCIDENT_NO_DECISION = "IncidentNoDecision"
ET_INCIDENT_TIMEOUT = "IncidentTimeout"

DECISION_NO_DECISION = "no-decision"
DECISION_TIMEOUT = "decision-timeout"

TIMEOUT_THRESHOLD_MINUTES = 15

STATUS_REPORTED = "REPORTED"
STATUS_DISPATCHED = "DISPATCHED"
STATUS_MONITORED = "MONITORED"
STATUS_ACKNOWLEDGED = "ACKNOWLEDGED"
STATUS_ESCALATED = "ESCALATED"

SEVERITY__LOW = "low"
SEVERITY__HIGH = "high"
SEVERITY__CRITICAL = "critical"

SEVERITY_LEVELS = {SEVERITY__LOW, SEVERITY__HIGH, SEVERITY__CRITICAL}